services:
  node-app:
    image: node:22.9.0  # 使用官方 Node.js 最新镜像
    working_dir: /app  # 设置容器的工作目录
    volumes:
      - .:/app       # 挂载当前目录到容器中的 /app 目录
      - /app/node_modules  # 防止覆盖 node_modules
    ports:
      - "3000:3000"  # 将容器的 3000 端口映射到主机的 3000 端口
    command: bash -c "npm install && npm start"  # 安装依赖并启动应用
    environment:
      - NODE_ENV=development